package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'BuildFreeBsd'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id("BuildFreeBsd")
    name = "Build (FreeBsd)"

    params {
        param("env.JAVA_HOME", "%macos.java8.oracle.64bit%")
    }

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        gradle {
            tasks = "clean build -I gradle/init-scripts/build-scan.init.gradle.kts"
            buildFile = ""
        }
    }

    features {
        commitStatusPublisher {
            vcsRootExtId = "${DslContext.settingsRoot.id}"
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:5306bfc7-041e-46e8-8d61-1d49424e7b04"
                }
            }
        }
    }

    requirements {
        contains("teamcity.agent.jvm.os.name", "Mac OS X")
    }
}))

