package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Publishing'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Publishing")) {
    cleanup {
        add {
            keepRule {
                id = "KEEP_RULE_1"
                keepAtLeast = builds(10)
                dataToKeep = everything()
                applyPerEachBranch = true
                preserveArtifactsDependencies = true
            }
        }
    }
}
