import org.gradle.api.file.DirectoryProperty;

public interface JniExtension {
    /**
     * The location for the header files generated by the {@link JniPlugin}.
     */
    DirectoryProperty getGeneratedHeadersDirectory();
}
