import org.gradle.api.file.DirectoryProperty;

public interface JniExtension {
    /**
     * The directory to place the <pre>native.h</pre> header file,
     * generated by the {@link JniPlugin}.
     */
    DirectoryProperty getGeneratedHeaderDirectory();
}
