import org.gradle.api.file.RegularFileProperty;

public interface JniExtension {
    /**
     * The location for the header file generated by the {@link JniPlugin}.
     */
    RegularFileProperty getGeneratedHeader();
}
