package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HttpsGithubComGradleNativePlatformGitRefsHeadsMaster1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("HttpsGithubComGradleNativePlatformGitRefsHeadsMaster1")
    name = "https://github.com/gradle/native-platform.git#refs/heads/master (1)"
    url = "https://github.com/gradle/native-platform.git"
    branchSpec = """
        +:refs/heads/*
        +:refs/(pull/*/head)
    """.trimIndent()
    authMethod = password {
        userName = "bot-teamcity"
        password = "credentialsJSON:5fe7c16b-cef8-4e22-a305-52f6ae768b72"
    }
}))

