name: add-to-gh-projects

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_GRADLE_GH_ORG_BOARD_ACCESS_TOKEN }}

jobs:
  add_to_gh_projects:
    name: Adds issues to GH projects
    runs-on: ubuntu-latest
    steps:
      - name: Add labeled issues to GH projects
        uses: gradle/build-tool-issue-automation-actions/add-labeled-issues@v1
